
package com.br.food.totem;

public class abaHambugue extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(abaHambugue.class.getName());

    /**
     * Creates new form abaHambugue
     */
    public abaHambugue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHamburgue = new javax.swing.JLabel();
        hambugueTipo4 = new javax.swing.JButton();
        hambugueTipo1 = new javax.swing.JButton();
        hambugueTipo2 = new javax.swing.JButton();
        hambugueTipo3 = new javax.swing.JButton();
        lbTipo1 = new javax.swing.JLabel();
        lbTipo2 = new javax.swing.JLabel();
        lbTipo3 = new javax.swing.JLabel();
        lbTipo4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 520));

        lbHamburgue.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbHamburgue.setText("Hamburgue");

        hambugueTipo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/food/totem/hamburgue.png"))); // NOI18N
        hambugueTipo4.addActionListener(this::hambugueTipo4ActionPerformed);

        hambugueTipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/food/totem/hamburgue.png"))); // NOI18N
        hambugueTipo1.addActionListener(this::hambugueTipo1ActionPerformed);

        hambugueTipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/food/totem/hamburgue.png"))); // NOI18N
        hambugueTipo2.addActionListener(this::hambugueTipo2ActionPerformed);

        hambugueTipo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/food/totem/hamburgue.png"))); // NOI18N
        hambugueTipo3.addActionListener(this::hambugueTipo3ActionPerformed);

        lbTipo1.setText("tipo 1");

        lbTipo2.setText("tipo 2");

        lbTipo3.setText("tipo3");

        lbTipo4.setText("tipo 4");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("29,99");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setText("19,99");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setText("39,99");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel4.setText("9,99");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(lbTipo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(lbTipo2)
                                .addGap(24, 24, 24))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLabel2))
                                    .addComponent(hambugueTipo2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(86, 86, 86)
                                .addComponent(lbTipo3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(hambugueTipo4, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lbTipo4)
                                    .addGap(21, 21, 21))))))
                .addGap(83, 83, 83))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(lbHamburgue))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(hambugueTipo3)
                            .addComponent(hambugueTipo1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(10, 10, 10)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbHamburgue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo1)
                    .addComponent(lbTipo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hambugueTipo2)
                    .addComponent(hambugueTipo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTipo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hambugueTipo3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTipo4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hambugueTipo4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hambugueTipo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hambugueTipo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hambugueTipo4ActionPerformed

    private void hambugueTipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hambugueTipo1ActionPerformed
         java.awt.EventQueue.invokeLater(() -> new personalizarHambugue().setVisible(true));
    }//GEN-LAST:event_hambugueTipo1ActionPerformed

    private void hambugueTipo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hambugueTipo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hambugueTipo2ActionPerformed

    private void hambugueTipo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hambugueTipo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hambugueTipo3ActionPerformed

    /**
     * @param args the command line arguments
     */
   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hambugueTipo1;
    private javax.swing.JButton hambugueTipo2;
    private javax.swing.JButton hambugueTipo3;
    private javax.swing.JButton hambugueTipo4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lbHamburgue;
    private javax.swing.JLabel lbTipo1;
    private javax.swing.JLabel lbTipo2;
    private javax.swing.JLabel lbTipo3;
    private javax.swing.JLabel lbTipo4;
    // End of variables declaration//GEN-END:variables
}
