/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.br.food.totem;

/**
 *
 * @author leons
 */
public class abaHambugue extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(abaHambugue.class.getName());

    /**
     * Creates new form abaHambugue
     */
    public abaHambugue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbHamburgue = new javax.swing.JLabel();
        hambugueTipo4 = new javax.swing.JButton();
        hambugueTipo1 = new javax.swing.JButton();
        hambugueTipo2 = new javax.swing.JButton();
        hambugueTipo3 = new javax.swing.JButton();
        lbTipo1 = new javax.swing.JLabel();
        lbTipo2 = new javax.swing.JLabel();
        lbTipo3 = new javax.swing.JLabel();
        lbTipo4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 520));

        lbHamburgue.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbHamburgue.setText("Hamburgue");

        hambugueTipo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/food/totem/hamburgue.png"))); // NOI18N
        hambugueTipo4.addActionListener(this::hambugueTipo4ActionPerformed);

        hambugueTipo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/food/totem/hamburgue.png"))); // NOI18N
        hambugueTipo1.addActionListener(this::hambugueTipo1ActionPerformed);

        hambugueTipo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/food/totem/hamburgue.png"))); // NOI18N
        hambugueTipo2.addActionListener(this::hambugueTipo2ActionPerformed);

        hambugueTipo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/food/totem/hamburgue.png"))); // NOI18N
        hambugueTipo3.addActionListener(this::hambugueTipo3ActionPerformed);

        lbTipo1.setText("tipo 1");

        lbTipo2.setText("tipo 2");

        lbTipo3.setText("tipo3");

        lbTipo4.setText("tipo 4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hambugueTipo1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                        .addComponent(hambugueTipo2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(hambugueTipo3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hambugueTipo4)))
                .addGap(95, 95, 95))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(lbTipo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTipo2)
                .addGap(119, 119, 119))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(lbTipo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbTipo4)
                .addGap(116, 116, 116))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lbHamburgue)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lbHamburgue)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTipo1)
                    .addComponent(lbTipo2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(hambugueTipo2)
                    .addComponent(hambugueTipo1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbTipo4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbTipo3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(hambugueTipo3)
                    .addComponent(hambugueTipo4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(127, 127, 127))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hambugueTipo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hambugueTipo4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hambugueTipo4ActionPerformed

    private void hambugueTipo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hambugueTipo1ActionPerformed
         java.awt.EventQueue.invokeLater(() -> new personalizarHambugue().setVisible(true));
    }//GEN-LAST:event_hambugueTipo1ActionPerformed

    private void hambugueTipo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hambugueTipo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hambugueTipo2ActionPerformed

    private void hambugueTipo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hambugueTipo3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hambugueTipo3ActionPerformed

    /**
     * @param args the command line arguments
     */
   
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hambugueTipo1;
    private javax.swing.JButton hambugueTipo2;
    private javax.swing.JButton hambugueTipo3;
    private javax.swing.JButton hambugueTipo4;
    private javax.swing.JLabel lbHamburgue;
    private javax.swing.JLabel lbTipo1;
    private javax.swing.JLabel lbTipo2;
    private javax.swing.JLabel lbTipo3;
    private javax.swing.JLabel lbTipo4;
    // End of variables declaration//GEN-END:variables
}
