/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.br.food.totem;

/**
 *
 * @author leons
 */
public class personalizarHambugue extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(personalizarHambugue.class.getName());

    /**
     * Creates new form personalizarHambugue
     */
    public personalizarHambugue() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbPersonalizar = new javax.swing.JLabel();
        lbNomeHambuguePersonalizar = new javax.swing.JLabel();
        lbIconeHamburguePersonalizar = new javax.swing.JLabel();
        lbQuantidadePersonalizar = new javax.swing.JLabel();
        lbItensOpcionaisPersonalizar = new javax.swing.JLabel();
        lbPromocao = new javax.swing.JLabel();
        tfItensOpcionais = new javax.swing.JTextField();
        cbCombo1 = new javax.swing.JCheckBox();
        cbCombo2 = new javax.swing.JCheckBox();
        cbCombo3 = new javax.swing.JCheckBox();
        tfQuantidade = new javax.swing.JTextField();
        lbIconeCombo1 = new javax.swing.JLabel();
        lbIconeCombo2 = new javax.swing.JLabel();
        lbIconeCombo3 = new javax.swing.JLabel();
        btContinuar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbPersonalizar.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        lbPersonalizar.setText("Personalizar");

        lbNomeHambuguePersonalizar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lbNomeHambuguePersonalizar.setText("Tipo 1");

        lbIconeHamburguePersonalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/food/totem/hamburgue.png"))); // NOI18N

        lbQuantidadePersonalizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbQuantidadePersonalizar.setText("Quantidade: ");

        lbItensOpcionaisPersonalizar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbItensOpcionaisPersonalizar.setText("Itens opcionais:");

        lbPromocao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbPromocao.setText("Promoções ");

        tfItensOpcionais.addActionListener(this::tfItensOpcionaisActionPerformed);

        cbCombo1.setText("Combo 1");
        cbCombo1.addActionListener(this::cbCombo1ActionPerformed);

        cbCombo2.setText("Combo 2");
        cbCombo2.addActionListener(this::cbCombo2ActionPerformed);

        cbCombo3.setText("Combo 3");

        tfQuantidade.addActionListener(this::tfQuantidadeActionPerformed);

        lbIconeCombo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/food/totem/combo.png"))); // NOI18N

        lbIconeCombo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/food/totem/combo.png"))); // NOI18N

        lbIconeCombo3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/br/food/totem/combo.png"))); // NOI18N

        btContinuar.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        btContinuar.setText("Continuar");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 27)); // NOI18N
        jButton1.setText("Finalizar");
        jButton1.setToolTipText("");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbPersonalizar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCombo1)
                                    .addComponent(lbIconeCombo1))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbCombo2)
                                    .addComponent(lbIconeCombo2))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbIconeCombo3)
                                    .addComponent(cbCombo3)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(lbNomeHambuguePersonalizar))
                                    .addComponent(lbIconeHamburguePersonalizar))
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfItensOpcionais, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lbPromocao)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbQuantidadePersonalizar)
                                            .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lbItensOpcionaisPersonalizar)
                                        .addGap(48, 48, 48))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbPersonalizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbNomeHambuguePersonalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbIconeHamburguePersonalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbQuantidadePersonalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbItensOpcionaisPersonalizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfItensOpcionais, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbPromocao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbIconeCombo1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIconeCombo2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbIconeCombo3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCombo1)
                    .addComponent(cbCombo2)
                    .addComponent(cbCombo3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfItensOpcionaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfItensOpcionaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfItensOpcionaisActionPerformed

    private void tfQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfQuantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfQuantidadeActionPerformed

    private void cbCombo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCombo1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCombo1ActionPerformed

    private void cbCombo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCombo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCombo2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         java.awt.EventQueue.invokeLater(() -> new ParaViagemTela().setVisible(true));
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btContinuar;
    private javax.swing.JCheckBox cbCombo1;
    private javax.swing.JCheckBox cbCombo2;
    private javax.swing.JCheckBox cbCombo3;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel lbIconeCombo1;
    private javax.swing.JLabel lbIconeCombo2;
    private javax.swing.JLabel lbIconeCombo3;
    private javax.swing.JLabel lbIconeHamburguePersonalizar;
    private javax.swing.JLabel lbItensOpcionaisPersonalizar;
    private javax.swing.JLabel lbNomeHambuguePersonalizar;
    private javax.swing.JLabel lbPersonalizar;
    private javax.swing.JLabel lbPromocao;
    private javax.swing.JLabel lbQuantidadePersonalizar;
    private javax.swing.JTextField tfItensOpcionais;
    private javax.swing.JTextField tfQuantidade;
    // End of variables declaration//GEN-END:variables
}
